name: just-test
on: 
  workflow_dispatch: 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v4
      -  name: single command
         run: sleep 5

      - name: multiple commands
        run: |
          echo "hello world"
          echo "hello aadil"
          echo "blabla"
          cat hello-file
  
  
